cache:  
  directories:  
   - $HOME/.m2
sudo: false  
language: java    
matrix:
 include:
 - os: linux
   jdk: oraclejdk8
 - os: osx
   osx_image: xcode8.2
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
install: mvn package -B
script: xvfb-run mvn verify -B
