/*
 * KLIFS API
 * Dynamically interact with the rich content of KLIFS: the structural kinase database
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;


/**
 * IFPList
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-05T09:28:37.207+02:00")
public class IFPList   {
  @SerializedName("structure_ID")
  private Integer structureID = null;

  @SerializedName("IFP")
  private String IFP = null;

  public IFPList structureID(Integer structureID) {
    this.structureID = structureID;
    return this;
  }

   /**
   * Get structureID
   * @return structureID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStructureID() {
    return structureID;
  }

  public void setStructureID(Integer structureID) {
    this.structureID = structureID;
  }

  public IFPList IFP(String IFP) {
    this.IFP = IFP;
    return this;
  }

   /**
   * Get IFP
   * @return IFP
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIFP() {
    return IFP;
  }

  public void setIFP(String IFP) {
    this.IFP = IFP;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IFPList iFPList = (IFPList) o;
    return Objects.equals(this.structureID, iFPList.structureID) &&
        Objects.equals(this.IFP, iFPList.IFP);
  }

  @Override
  public int hashCode() {
    return Objects.hash(structureID, IFP);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IFPList {\n");
    
    sb.append("    structureID: ").append(toIndentedString(structureID)).append("\n");
    sb.append("    IFP: ").append(toIndentedString(IFP)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

