/*
 * KLIFS API
 * Dynamically interact with the rich content of KLIFS: the structural kinase database
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;


/**
 * KinaseInformation
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-05T09:28:37.207+02:00")
public class KinaseInformation   {
  @SerializedName("kinase_ID")
  private Integer kinaseID = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("HGNC")
  private String HGNC = null;

  @SerializedName("family")
  private String family = null;

  @SerializedName("group")
  private String group = null;

  @SerializedName("kinase_class")
  private String kinaseClass = null;

  @SerializedName("species")
  private String species = null;

  @SerializedName("full_name")
  private String fullName = null;

  @SerializedName("uniprot")
  private String uniprot = null;

  @SerializedName("iuphar")
  private String iuphar = null;

  @SerializedName("pocket")
  private String pocket = null;

  public KinaseInformation kinaseID(Integer kinaseID) {
    this.kinaseID = kinaseID;
    return this;
  }

   /**
   * Get kinaseID
   * @return kinaseID
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getKinaseID() {
    return kinaseID;
  }

  public void setKinaseID(Integer kinaseID) {
    this.kinaseID = kinaseID;
  }

  public KinaseInformation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public KinaseInformation HGNC(String HGNC) {
    this.HGNC = HGNC;
    return this;
  }

   /**
   * Get HGNC
   * @return HGNC
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHGNC() {
    return HGNC;
  }

  public void setHGNC(String HGNC) {
    this.HGNC = HGNC;
  }

  public KinaseInformation family(String family) {
    this.family = family;
    return this;
  }

   /**
   * Get family
   * @return family
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFamily() {
    return family;
  }

  public void setFamily(String family) {
    this.family = family;
  }

  public KinaseInformation group(String group) {
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGroup() {
    return group;
  }

  public void setGroup(String group) {
    this.group = group;
  }

  public KinaseInformation kinaseClass(String kinaseClass) {
    this.kinaseClass = kinaseClass;
    return this;
  }

   /**
   * Get kinaseClass
   * @return kinaseClass
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getKinaseClass() {
    return kinaseClass;
  }

  public void setKinaseClass(String kinaseClass) {
    this.kinaseClass = kinaseClass;
  }

  public KinaseInformation species(String species) {
    this.species = species;
    return this;
  }

   /**
   * Get species
   * @return species
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSpecies() {
    return species;
  }

  public void setSpecies(String species) {
    this.species = species;
  }

  public KinaseInformation fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public KinaseInformation uniprot(String uniprot) {
    this.uniprot = uniprot;
    return this;
  }

   /**
   * Get uniprot
   * @return uniprot
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUniprot() {
    return uniprot;
  }

  public void setUniprot(String uniprot) {
    this.uniprot = uniprot;
  }

  public KinaseInformation iuphar(String iuphar) {
    this.iuphar = iuphar;
    return this;
  }

   /**
   * Get iuphar
   * @return iuphar
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIuphar() {
    return iuphar;
  }

  public void setIuphar(String iuphar) {
    this.iuphar = iuphar;
  }

  public KinaseInformation pocket(String pocket) {
    this.pocket = pocket;
    return this;
  }

   /**
   * Get pocket
   * @return pocket
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPocket() {
    return pocket;
  }

  public void setPocket(String pocket) {
    this.pocket = pocket;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KinaseInformation kinaseInformation = (KinaseInformation) o;
    return Objects.equals(this.kinaseID, kinaseInformation.kinaseID) &&
        Objects.equals(this.name, kinaseInformation.name) &&
        Objects.equals(this.HGNC, kinaseInformation.HGNC) &&
        Objects.equals(this.family, kinaseInformation.family) &&
        Objects.equals(this.group, kinaseInformation.group) &&
        Objects.equals(this.kinaseClass, kinaseInformation.kinaseClass) &&
        Objects.equals(this.species, kinaseInformation.species) &&
        Objects.equals(this.fullName, kinaseInformation.fullName) &&
        Objects.equals(this.uniprot, kinaseInformation.uniprot) &&
        Objects.equals(this.iuphar, kinaseInformation.iuphar) &&
        Objects.equals(this.pocket, kinaseInformation.pocket);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kinaseID, name, HGNC, family, group, kinaseClass, species, fullName, uniprot, iuphar, pocket);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KinaseInformation {\n");
    
    sb.append("    kinaseID: ").append(toIndentedString(kinaseID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    HGNC: ").append(toIndentedString(HGNC)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    kinaseClass: ").append(toIndentedString(kinaseClass)).append("\n");
    sb.append("    species: ").append(toIndentedString(species)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    uniprot: ").append(toIndentedString(uniprot)).append("\n");
    sb.append("    iuphar: ").append(toIndentedString(iuphar)).append("\n");
    sb.append("    pocket: ").append(toIndentedString(pocket)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

