/*
 * KLIFS API
 * Dynamically interact with the rich content of KLIFS: the structural kinase database
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * LigandDetails
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-05T09:28:37.207+02:00")
public class LigandDetails   {
  @SerializedName("ligand_ID")
  private Integer ligandID = null;

  @SerializedName("PDB-code")
  private String pDBCode = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("SMILES")
  private String SMILES = null;

  @SerializedName("InChIKey")
  private String inChIKey = null;

  public LigandDetails ligandID(Integer ligandID) {
    this.ligandID = ligandID;
    return this;
  }

   /**
   * KLIFS ID for a specific kinase structure
   * @return ligandID
  **/
  @ApiModelProperty(example = "null", required = true, value = "KLIFS ID for a specific kinase structure")
  public Integer getLigandID() {
    return ligandID;
  }

  public void setLigandID(Integer ligandID) {
    this.ligandID = ligandID;
  }

  public LigandDetails pDBCode(String pDBCode) {
    this.pDBCode = pDBCode;
    return this;
  }

   /**
   * 3-letter PDB-code for a specific ligand
   * @return pDBCode
  **/
  @ApiModelProperty(example = "null", required = true, value = "3-letter PDB-code for a specific ligand")
  public String getPDBCode() {
    return pDBCode;
  }

  public void setPDBCode(String pDBCode) {
    this.pDBCode = pDBCode;
  }

  public LigandDetails name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the ligand
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Name of the ligand")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LigandDetails SMILES(String SMILES) {
    this.SMILES = SMILES;
    return this;
  }

   /**
   * SMILES code for a specific ligand
   * @return SMILES
  **/
  @ApiModelProperty(example = "null", value = "SMILES code for a specific ligand")
  public String getSMILES() {
    return SMILES;
  }

  public void setSMILES(String SMILES) {
    this.SMILES = SMILES;
  }

  public LigandDetails inChIKey(String inChIKey) {
    this.inChIKey = inChIKey;
    return this;
  }

   /**
   * InChiKey of a specific ligand
   * @return inChIKey
  **/
  @ApiModelProperty(example = "null", value = "InChiKey of a specific ligand")
  public String getInChIKey() {
    return inChIKey;
  }

  public void setInChIKey(String inChIKey) {
    this.inChIKey = inChIKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LigandDetails ligandDetails = (LigandDetails) o;
    return Objects.equals(this.ligandID, ligandDetails.ligandID) &&
        Objects.equals(this.pDBCode, ligandDetails.pDBCode) &&
        Objects.equals(this.name, ligandDetails.name) &&
        Objects.equals(this.SMILES, ligandDetails.SMILES) &&
        Objects.equals(this.inChIKey, ligandDetails.inChIKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ligandID, pDBCode, name, SMILES, inChIKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LigandDetails {\n");
    
    sb.append("    ligandID: ").append(toIndentedString(ligandID)).append("\n");
    sb.append("    pDBCode: ").append(toIndentedString(pDBCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    SMILES: ").append(toIndentedString(SMILES)).append("\n");
    sb.append("    inChIKey: ").append(toIndentedString(inChIKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

