/*
 * KLIFS API
 * Dynamically interact with the rich content of KLIFS: the structural kinase database
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;


/**
 * MatchList
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-05T09:28:37.207+02:00")
public class MatchList   {
  @SerializedName("index")
  private Integer index = null;

  @SerializedName("Xray_position")
  private String xrayPosition = null;

  @SerializedName("KLIFS_position")
  private String kLIFSPosition = null;

  public MatchList index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Get index
   * @return index
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public MatchList xrayPosition(String xrayPosition) {
    this.xrayPosition = xrayPosition;
    return this;
  }

   /**
   * Get xrayPosition
   * @return xrayPosition
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getXrayPosition() {
    return xrayPosition;
  }

  public void setXrayPosition(String xrayPosition) {
    this.xrayPosition = xrayPosition;
  }

  public MatchList kLIFSPosition(String kLIFSPosition) {
    this.kLIFSPosition = kLIFSPosition;
    return this;
  }

   /**
   * Get kLIFSPosition
   * @return kLIFSPosition
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getKLIFSPosition() {
    return kLIFSPosition;
  }

  public void setKLIFSPosition(String kLIFSPosition) {
    this.kLIFSPosition = kLIFSPosition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchList matchList = (MatchList) o;
    return Objects.equals(this.index, matchList.index) &&
        Objects.equals(this.xrayPosition, matchList.xrayPosition) &&
        Objects.equals(this.kLIFSPosition, matchList.kLIFSPosition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, xrayPosition, kLIFSPosition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchList {\n");
    
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    xrayPosition: ").append(toIndentedString(xrayPosition)).append("\n");
    sb.append("    kLIFSPosition: ").append(toIndentedString(kLIFSPosition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

