/*
 * KLIFS API
 * Dynamically interact with the rich content of KLIFS: the structural kinase database
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BioactivityDetails
 */
public class BioactivityDetailsTest {
    private final BioactivityDetails model = new BioactivityDetails();

    /**
     * Model tests for BioactivityDetails
     */
    @Test
    public void testBioactivityDetails() {
        // TODO: test BioactivityDetails
    }

    /**
     * Test the property 'prefName'
     */
    @Test
    public void prefNameTest() {
        // TODO: test prefName
    }

    /**
     * Test the property 'accession'
     */
    @Test
    public void accessionTest() {
        // TODO: test accession
    }

    /**
     * Test the property 'organism'
     */
    @Test
    public void organismTest() {
        // TODO: test organism
    }

    /**
     * Test the property 'standardType'
     */
    @Test
    public void standardTypeTest() {
        // TODO: test standardType
    }

    /**
     * Test the property 'standardRelation'
     */
    @Test
    public void standardRelationTest() {
        // TODO: test standardRelation
    }

    /**
     * Test the property 'standardValue'
     */
    @Test
    public void standardValueTest() {
        // TODO: test standardValue
    }

    /**
     * Test the property 'standardUnits'
     */
    @Test
    public void standardUnitsTest() {
        // TODO: test standardUnits
    }

    /**
     * Test the property 'pchemblValue'
     */
    @Test
    public void pchemblValueTest() {
        // TODO: test pchemblValue
    }

}
