/*
 * KLIFS API
 * Dynamically interact with the rich content of KLIFS: the structural kinase database
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for KinaseInformation
 */
public class KinaseInformationTest {
    private final KinaseInformation model = new KinaseInformation();

    /**
     * Model tests for KinaseInformation
     */
    @Test
    public void testKinaseInformation() {
        // TODO: test KinaseInformation
    }

    /**
     * Test the property 'kinaseID'
     */
    @Test
    public void kinaseIDTest() {
        // TODO: test kinaseID
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'HGNC'
     */
    @Test
    public void HGNCTest() {
        // TODO: test HGNC
    }

    /**
     * Test the property 'family'
     */
    @Test
    public void familyTest() {
        // TODO: test family
    }

    /**
     * Test the property 'group'
     */
    @Test
    public void groupTest() {
        // TODO: test group
    }

    /**
     * Test the property 'kinaseClass'
     */
    @Test
    public void kinaseClassTest() {
        // TODO: test kinaseClass
    }

    /**
     * Test the property 'species'
     */
    @Test
    public void speciesTest() {
        // TODO: test species
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'uniprot'
     */
    @Test
    public void uniprotTest() {
        // TODO: test uniprot
    }

    /**
     * Test the property 'iuphar'
     */
    @Test
    public void iupharTest() {
        // TODO: test iuphar
    }

    /**
     * Test the property 'pocket'
     */
    @Test
    public void pocketTest() {
        // TODO: test pocket
    }

}
