/*
 * KLIFS API
 * Dynamically interact with the rich content of KLIFS: the structural kinase database
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LigandDetails
 */
public class LigandDetailsTest {
    private final LigandDetails model = new LigandDetails();

    /**
     * Model tests for LigandDetails
     */
    @Test
    public void testLigandDetails() {
        // TODO: test LigandDetails
    }

    /**
     * Test the property 'ligandID'
     */
    @Test
    public void ligandIDTest() {
        // TODO: test ligandID
    }

    /**
     * Test the property 'pdBCode'
     */
    @Test
    public void pdBCodeTest() {
        // TODO: test pdBCode
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'SMILES'
     */
    @Test
    public void SMILESTest() {
        // TODO: test SMILES
    }

    /**
     * Test the property 'inChIKey'
     */
    @Test
    public void inChIKeyTest() {
        // TODO: test inChIKey
    }

}
