/*
 * KLIFS API
 * Dynamically interact with the rich content of KLIFS: the structural kinase database
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MatchList
 */
public class MatchListTest {
    private final MatchList model = new MatchList();

    /**
     * Model tests for MatchList
     */
    @Test
    public void testMatchList() {
        // TODO: test MatchList
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'xrayPosition'
     */
    @Test
    public void xrayPositionTest() {
        // TODO: test xrayPosition
    }

    /**
     * Test the property 'klIFSPosition'
     */
    @Test
    public void klIFSPositionTest() {
        // TODO: test klIFSPosition
    }

}
