/*
 * KLIFS API
 * Dynamically interact with the rich content of KLIFS: the structural kinase database
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * KinaseInformation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-21T14:12:18.837505154+01:00[Europe/Amsterdam]")
public class KinaseInformation {
  public static final String SERIALIZED_NAME_KINASE_I_D = "kinase_ID";
  @SerializedName(SERIALIZED_NAME_KINASE_I_D)
  private Integer kinaseID;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_H_G_N_C = "HGNC";
  @SerializedName(SERIALIZED_NAME_H_G_N_C)
  private String HGNC;

  public static final String SERIALIZED_NAME_FAMILY = "family";
  @SerializedName(SERIALIZED_NAME_FAMILY)
  private String family;

  public static final String SERIALIZED_NAME_GROUP = "group";
  @SerializedName(SERIALIZED_NAME_GROUP)
  private String group;

  public static final String SERIALIZED_NAME_KINASE_CLASS = "kinase_class";
  @SerializedName(SERIALIZED_NAME_KINASE_CLASS)
  private String kinaseClass;

  public static final String SERIALIZED_NAME_SPECIES = "species";
  @SerializedName(SERIALIZED_NAME_SPECIES)
  private String species;

  public static final String SERIALIZED_NAME_FULL_NAME = "full_name";
  @SerializedName(SERIALIZED_NAME_FULL_NAME)
  private String fullName;

  public static final String SERIALIZED_NAME_UNIPROT = "uniprot";
  @SerializedName(SERIALIZED_NAME_UNIPROT)
  private String uniprot;

  public static final String SERIALIZED_NAME_IUPHAR = "iuphar";
  @SerializedName(SERIALIZED_NAME_IUPHAR)
  private String iuphar;

  public static final String SERIALIZED_NAME_POCKET = "pocket";
  @SerializedName(SERIALIZED_NAME_POCKET)
  private String pocket;

  public KinaseInformation() {
  }

  public KinaseInformation kinaseID(Integer kinaseID) {
    
    this.kinaseID = kinaseID;
    return this;
  }

   /**
   * Get kinaseID
   * @return kinaseID
  **/
  @javax.annotation.Nullable
  public Integer getKinaseID() {
    return kinaseID;
  }


  public void setKinaseID(Integer kinaseID) {
    this.kinaseID = kinaseID;
  }


  public KinaseInformation name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public KinaseInformation HGNC(String HGNC) {
    
    this.HGNC = HGNC;
    return this;
  }

   /**
   * Get HGNC
   * @return HGNC
  **/
  @javax.annotation.Nullable
  public String getHGNC() {
    return HGNC;
  }


  public void setHGNC(String HGNC) {
    this.HGNC = HGNC;
  }


  public KinaseInformation family(String family) {
    
    this.family = family;
    return this;
  }

   /**
   * Get family
   * @return family
  **/
  @javax.annotation.Nullable
  public String getFamily() {
    return family;
  }


  public void setFamily(String family) {
    this.family = family;
  }


  public KinaseInformation group(String group) {
    
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  @javax.annotation.Nullable
  public String getGroup() {
    return group;
  }


  public void setGroup(String group) {
    this.group = group;
  }


  public KinaseInformation kinaseClass(String kinaseClass) {
    
    this.kinaseClass = kinaseClass;
    return this;
  }

   /**
   * Get kinaseClass
   * @return kinaseClass
  **/
  @javax.annotation.Nullable
  public String getKinaseClass() {
    return kinaseClass;
  }


  public void setKinaseClass(String kinaseClass) {
    this.kinaseClass = kinaseClass;
  }


  public KinaseInformation species(String species) {
    
    this.species = species;
    return this;
  }

   /**
   * Get species
   * @return species
  **/
  @javax.annotation.Nullable
  public String getSpecies() {
    return species;
  }


  public void setSpecies(String species) {
    this.species = species;
  }


  public KinaseInformation fullName(String fullName) {
    
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @javax.annotation.Nullable
  public String getFullName() {
    return fullName;
  }


  public void setFullName(String fullName) {
    this.fullName = fullName;
  }


  public KinaseInformation uniprot(String uniprot) {
    
    this.uniprot = uniprot;
    return this;
  }

   /**
   * Get uniprot
   * @return uniprot
  **/
  @javax.annotation.Nullable
  public String getUniprot() {
    return uniprot;
  }


  public void setUniprot(String uniprot) {
    this.uniprot = uniprot;
  }


  public KinaseInformation iuphar(String iuphar) {
    
    this.iuphar = iuphar;
    return this;
  }

   /**
   * Get iuphar
   * @return iuphar
  **/
  @javax.annotation.Nullable
  public String getIuphar() {
    return iuphar;
  }


  public void setIuphar(String iuphar) {
    this.iuphar = iuphar;
  }


  public KinaseInformation pocket(String pocket) {
    
    this.pocket = pocket;
    return this;
  }

   /**
   * Get pocket
   * @return pocket
  **/
  @javax.annotation.Nullable
  public String getPocket() {
    return pocket;
  }


  public void setPocket(String pocket) {
    this.pocket = pocket;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KinaseInformation kinaseInformation = (KinaseInformation) o;
    return Objects.equals(this.kinaseID, kinaseInformation.kinaseID) &&
        Objects.equals(this.name, kinaseInformation.name) &&
        Objects.equals(this.HGNC, kinaseInformation.HGNC) &&
        Objects.equals(this.family, kinaseInformation.family) &&
        Objects.equals(this.group, kinaseInformation.group) &&
        Objects.equals(this.kinaseClass, kinaseInformation.kinaseClass) &&
        Objects.equals(this.species, kinaseInformation.species) &&
        Objects.equals(this.fullName, kinaseInformation.fullName) &&
        Objects.equals(this.uniprot, kinaseInformation.uniprot) &&
        Objects.equals(this.iuphar, kinaseInformation.iuphar) &&
        Objects.equals(this.pocket, kinaseInformation.pocket);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kinaseID, name, HGNC, family, group, kinaseClass, species, fullName, uniprot, iuphar, pocket);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KinaseInformation {\n");
    sb.append("    kinaseID: ").append(toIndentedString(kinaseID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    HGNC: ").append(toIndentedString(HGNC)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    kinaseClass: ").append(toIndentedString(kinaseClass)).append("\n");
    sb.append("    species: ").append(toIndentedString(species)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    uniprot: ").append(toIndentedString(uniprot)).append("\n");
    sb.append("    iuphar: ").append(toIndentedString(iuphar)).append("\n");
    sb.append("    pocket: ").append(toIndentedString(pocket)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("kinase_ID");
    openapiFields.add("name");
    openapiFields.add("HGNC");
    openapiFields.add("family");
    openapiFields.add("group");
    openapiFields.add("kinase_class");
    openapiFields.add("species");
    openapiFields.add("full_name");
    openapiFields.add("uniprot");
    openapiFields.add("iuphar");
    openapiFields.add("pocket");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to KinaseInformation
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!KinaseInformation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in KinaseInformation is not found in the empty JSON string", KinaseInformation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!KinaseInformation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `KinaseInformation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("HGNC") != null && !jsonObj.get("HGNC").isJsonNull()) && !jsonObj.get("HGNC").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `HGNC` to be a primitive type in the JSON string but got `%s`", jsonObj.get("HGNC").toString()));
      }
      if ((jsonObj.get("family") != null && !jsonObj.get("family").isJsonNull()) && !jsonObj.get("family").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `family` to be a primitive type in the JSON string but got `%s`", jsonObj.get("family").toString()));
      }
      if ((jsonObj.get("group") != null && !jsonObj.get("group").isJsonNull()) && !jsonObj.get("group").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `group` to be a primitive type in the JSON string but got `%s`", jsonObj.get("group").toString()));
      }
      if ((jsonObj.get("kinase_class") != null && !jsonObj.get("kinase_class").isJsonNull()) && !jsonObj.get("kinase_class").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `kinase_class` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kinase_class").toString()));
      }
      if ((jsonObj.get("species") != null && !jsonObj.get("species").isJsonNull()) && !jsonObj.get("species").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `species` to be a primitive type in the JSON string but got `%s`", jsonObj.get("species").toString()));
      }
      if ((jsonObj.get("full_name") != null && !jsonObj.get("full_name").isJsonNull()) && !jsonObj.get("full_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `full_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("full_name").toString()));
      }
      if ((jsonObj.get("uniprot") != null && !jsonObj.get("uniprot").isJsonNull()) && !jsonObj.get("uniprot").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uniprot` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uniprot").toString()));
      }
      if ((jsonObj.get("iuphar") != null && !jsonObj.get("iuphar").isJsonNull()) && !jsonObj.get("iuphar").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `iuphar` to be a primitive type in the JSON string but got `%s`", jsonObj.get("iuphar").toString()));
      }
      if ((jsonObj.get("pocket") != null && !jsonObj.get("pocket").isJsonNull()) && !jsonObj.get("pocket").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pocket` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pocket").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!KinaseInformation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'KinaseInformation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<KinaseInformation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(KinaseInformation.class));

       return (TypeAdapter<T>) new TypeAdapter<KinaseInformation>() {
           @Override
           public void write(JsonWriter out, KinaseInformation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public KinaseInformation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of KinaseInformation given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of KinaseInformation
  * @throws IOException if the JSON string is invalid with respect to KinaseInformation
  */
  public static KinaseInformation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, KinaseInformation.class);
  }

 /**
  * Convert an instance of KinaseInformation to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

