/*
 * KLIFS API
 * Dynamically interact with the rich content of KLIFS: the structural kinase database
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * MatchList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-21T14:12:18.837505154+01:00[Europe/Amsterdam]")
public class MatchList {
  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_INDEX)
  private Integer index;

  public static final String SERIALIZED_NAME_XRAY_POSITION = "Xray_position";
  @SerializedName(SERIALIZED_NAME_XRAY_POSITION)
  private String xrayPosition;

  public static final String SERIALIZED_NAME_KL_I_F_S_POSITION = "KLIFS_position";
  @SerializedName(SERIALIZED_NAME_KL_I_F_S_POSITION)
  private String klIFSPosition;

  public MatchList() {
  }

  public MatchList index(Integer index) {
    
    this.index = index;
    return this;
  }

   /**
   * Get index
   * @return index
  **/
  @javax.annotation.Nullable
  public Integer getIndex() {
    return index;
  }


  public void setIndex(Integer index) {
    this.index = index;
  }


  public MatchList xrayPosition(String xrayPosition) {
    
    this.xrayPosition = xrayPosition;
    return this;
  }

   /**
   * Get xrayPosition
   * @return xrayPosition
  **/
  @javax.annotation.Nullable
  public String getXrayPosition() {
    return xrayPosition;
  }


  public void setXrayPosition(String xrayPosition) {
    this.xrayPosition = xrayPosition;
  }


  public MatchList klIFSPosition(String klIFSPosition) {
    
    this.klIFSPosition = klIFSPosition;
    return this;
  }

   /**
   * Get klIFSPosition
   * @return klIFSPosition
  **/
  @javax.annotation.Nullable
  public String getKlIFSPosition() {
    return klIFSPosition;
  }


  public void setKlIFSPosition(String klIFSPosition) {
    this.klIFSPosition = klIFSPosition;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchList matchList = (MatchList) o;
    return Objects.equals(this.index, matchList.index) &&
        Objects.equals(this.xrayPosition, matchList.xrayPosition) &&
        Objects.equals(this.klIFSPosition, matchList.klIFSPosition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, xrayPosition, klIFSPosition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchList {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    xrayPosition: ").append(toIndentedString(xrayPosition)).append("\n");
    sb.append("    klIFSPosition: ").append(toIndentedString(klIFSPosition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("index");
    openapiFields.add("Xray_position");
    openapiFields.add("KLIFS_position");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to MatchList
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MatchList.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MatchList is not found in the empty JSON string", MatchList.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MatchList.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MatchList` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("Xray_position") != null && !jsonObj.get("Xray_position").isJsonNull()) && !jsonObj.get("Xray_position").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Xray_position` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Xray_position").toString()));
      }
      if ((jsonObj.get("KLIFS_position") != null && !jsonObj.get("KLIFS_position").isJsonNull()) && !jsonObj.get("KLIFS_position").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `KLIFS_position` to be a primitive type in the JSON string but got `%s`", jsonObj.get("KLIFS_position").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MatchList.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MatchList' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MatchList> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MatchList.class));

       return (TypeAdapter<T>) new TypeAdapter<MatchList>() {
           @Override
           public void write(JsonWriter out, MatchList value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MatchList read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MatchList given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MatchList
  * @throws IOException if the JSON string is invalid with respect to MatchList
  */
  public static MatchList fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MatchList.class);
  }

 /**
  * Convert an instance of MatchList to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

